### ISSUE TITLE
Timeout on MODELRUN and SCRIPTRUN commands

### ISSUE THREAD

**Issue by K-Jo** [RedisAI/RedisAI#184]
Both commands should have a limited execution time that is configurable at module level.

**Comment by lantiga** [comment]
Design: have a watchdog thread that kills computing threads running for too long.
We will need:
- to move SCRIPTRUN in a compute thread (right now it's in the main thread, but the plan was to move anyway)
- create watchdog thread that keeps track of time
- figure out how we clean things up when we forcibly terminate the thread with `pthread_cancel` using `pthread_cleanup_push`, so that there are no leaks

**Comment by filipecosta90** [comment]
> Design: have a watchdog thread that kills computing threads running for too long.
> We will need:
> 
>     * to move SCRIPTRUN in a compute thread (right now it's in the main thread, but the plan was to move anyway)
> 
>     * create watchdog thread that keeps track of time
> 
>     * figure out how we clean things up when we forcibly terminate the thread with `pthread_cancel` using `pthread_cleanup_push`, so that there are no leaks

@lantiga the feature is already present on RedisModuleBlockClient via timeout_callback. We just need to implement it :)

**Comment by lantiga** [comment]
On second thought, interrupting an execution of a thread is beyond the scope here.

A TIMEOUT argument to MODELRUN would still be relevant, but to indicate that a job in the queue should be evicted (i.e. skipped and removed) from the queue if TIMEOUT has elapsed.

In other words, clients can declare that they are only interested in the computation if executed within TIMEOUT, otherwise no bother.

**Comment by lantiga** [comment]
Closed by #482
