### ISSUE TITLE
List all the models deployed

### ISSUE THREAD

**Issue by hhsecond** [RedisAI/RedisAI#303]
Currently, we don't have any mechanism to figure out the models deployed using RedisAI. While it is important to have an API to list all the models, It might be a good idea to have an API that lists scripts and tensors as well

**Comment by lantiga** [comment]
We will implement a command to list models and scripts, along with their TAGS (see #306) for identification. In order to do that, we can leverage on the shard-level dictionary that we maintain for AI.INFO.
I don't think we should list tensors - they could come in a very large number, it would be equivalent to a keyscan.
