### ISSUE TITLE
TensorRT

### ISSUE THREAD

**Issue by oqpti** [RedisAI/RedisAI#461]
What is the likelihood that Redis AI will support TensorRT engines in the near future? In spite of how lovely and convienent the redis platform is to use, Redis AI can't compete with Triton for performance limited applications until this is possible.

**Comment by lantiga** [comment]
For clarification (it may not be useful for you @oqpti, but it may be for others): Triton is an inference server (just like RedisAI) and both can use or not use TensorRT for executing (part of) computation graphs in an optimized way.

So TensorRT concerns the RedisAI backends, rather than RedisAI itself. For instance, you can leverage TensorRT it through the TensorFlow backend, thanks to TF-TRT (https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html) or through the ONNXRuntime backend, through the TensorRT execution provider (https://github.com/microsoft/onnxruntime/blob/master/docs/execution_providers/TensorRT-ExecutionProvider.md).
RedisAI stays exactly the same, but you load a specialized backend.

What we don't currently offer is a pre-packaged way to obtain a TensorRT-enabled backend, but that could be scheduled for the future in case there's interest.

/cc @filipecosta90 (who has experimented with TensorRT and RedisAI in the past)

**Comment by oqpti** [comment]
This actually does help, thank you!
