### ISSUE TITLE
Improve RAI_TensorSet_RedisCommand memory growth/page_fault code path by reusing already allocated redis BLOB

### ISSUE THREAD

**Issue by filipecosta90** [RedisAI/RedisAI#515]
We saw that on large tensors, for example an image with 1 x 3 x 224 x 224 ( 602 KiB ), the CPU cycles (wasted) on Allocator take a big chunk of the total redis-server main thread CPU cycles. In the example bellow we observe 42% wasted cpu cycles. 
We should investigate ways to improve it by testing reusing previously allocated command arg memory. Only possible for `BLOB` tensorsets...  
![image](https://user-images.githubusercontent.com/5832149/100437096-2e025880-3098-11eb-82f4-c4bc26400b96.png)

**Comment by lantiga** [comment]
We have two options:
1. check if a key being set in TENSORSET, MODELRUN OUTPUT, SCRIPTRUN OUTPUT or DAGRUN PERSIST contains a tensor with the same buffer size (in bytes) that we can re-use (instead of deallocating / reallocating)
2. keep a memory pool for tensors where we keep tensors for a while for reuse before deallocating them

The advantage of 2) is that we could use the pool whenever we need to allocate a tensor, irrespective of whether they are associated to an actual key (e.g. TENSORSET within a DAG). The downside is that the logic for the pool needs to be thought out well, especially the logic for deallocating, to avoid having a lot of allocated memory that is not used.
