### ISSUE TITLE
Potential error(e.g., deadlock) due to the unreleased lock &run_queue_info->run_queue_mutex

### ISSUE THREAD

**Issue by jenny-cheung** [RedisAI/RedisAI#812]
Dear Developers:
           First, thank you for your checking. The lock acquired at pthread_mutex_lock(&run_queue_info->run_queue_mutex); if the control flow goes to the break statement. The fix is to insert the unlock statement before breaking. Thank you.

https://github.com/RedisAI/RedisAI/blob/1fdc22b38a994f6e50287028c9ee44abcf636fab/src/execution/background_workers.c#L270

https://github.com/RedisAI/RedisAI/blob/1fdc22b38a994f6e50287028c9ee44abcf636fab/src/execution/background_workers.c#L290

```
void *BGWorker_ThreadMain(void *arg) {
    ...;
    pthread_mutex_lock(&run_queue_info->run_queue_mutex);

    while (true) {
        _BGThread_Wait(run_queue_info);
        // This is the length of the queue for this particular device
        // (see run_queue_info->devicestr).
        // There might be more than one thread operating on the same
        // queue, according to the THREADS_PER_QUEUE config variable.
        while (queueFront(run_queue_info->run_queue)) {
            array_clear(batch_rinfo);
            // We first peek the front of the queue
            queueItem *item = queuePop(run_queue_info->run_queue);
            RedisAI_RunInfo *rinfo = (RedisAI_RunInfo *)item->value;
            RedisModule_Free(item);
            // In case of timeout or error - skip execution.
            bool skip_execution = _BGThread_IsRInfoTimedOut(rinfo) || RedisAI_DagError(rinfo);
            // Prepare to execution, if the op or the batch is not ready, exit
            // the loop, give a chance to new tasks to submit.
            if (!skip_execution &&
                !_BGThread_PrepareExecution(run_queue_info, rinfo, &batch_rinfo)) {
                break;  // without being released if breaking
            }
           
        }
    }
    array_free(batch_rinfo);
}
```

**Comment by DvirDukhan** [comment]
Hi @jenny-cheung 
thanks for checking in on this.
This is by design: The mutex of the run queue is held locked by a background thread until it needs to execute OR it calls `_BGThread_Wait` to wait for additional possible inputs on the queue.
If the current task (head of the queue) is not ready, it is implicitly pushed back to the queue by the background worker (at `_BGThread_PrepareExecution`) and when the loop `break`s, the next thing to be called is `_BGThread_Wait` which do a timed wait on a conditional variable, that needs the mutex to be locked. As you can see in [`pthread_cond_timedwait`](https://linux.die.net/man/3/pthread_cond_timedwait) `man` page, this call automatically frees the lock.

Can you please describe the deadlock scenario you found?

**Comment by jenny-cheung** [comment]
@DvirDukhan Thank you for your detailed reply. This is not triggered but reported by a static analyzer.
